jiri: Fix bug in hook arg xml tag
The ",chardata,omitempty" causes the following failure:

ERROR: invalid manifest
/usr/local/google/home/toddw/fnl/.manifest/v2/mojo: xml: invalid tag in
field Arg of type project.HookArg: ",chardata,omitempty"

Change-Id: Iaebd4672782bd12900b28ce84e1ce154851e564f